version: '3'

services:

    #PHP Service
    sigga-app:
        container_name: sigga-app
        build: ./php
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - /var/www:/var/www
            - /var/www/sigga-infra/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - sigga-network

    #Nginx Service
    sigga-server:
        container_name: sigga-server
        build: ./nginx
        restart: unless-stopped
        tty: true
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/www:/var/www
            - /var/www/sigga-infra/nginx/conf.d/:/etc/nginx/conf.d/
            - /var/www/sigga-infra/certbot/conf:/etc/letsencrypt
            - /var/www/sigga-infra/certbot/www:/var/www/certbot
        networks:
            - sigga-network

    #MySQL Service
    sigga-database:
        container_name: sigga-database
        build: ./mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - /var/www/db/mysql:/var/lib/mysql
        environment:
            - MYSQL_HOST=127.0.0.1
            - MYSQL_PORT=3306
            - MYSQL_DATABASE=${DEFAULT_DATABASE}
            - MYSQL_USER=${DEFAULT_USER}
            - MYSQL_PASSWORD=${DEFAULT_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DEFAULT_ROOT_PASSWORD}
        networks:
            - sigga-network

    #Redis Service
    sigga-cache:
        container_name: sigga-cache
        build: ./redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - sigga-network

    sigga-certbot:
        container_name: sigga-certbot
        build: ./certbot
        restart: unless-stopped
        networks:
            - sigga-network
        volumes:
            - /var/www/sigga-infra/certbot/conf:/etc/letsencrypt
            - /var/www/sigga-infra/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

#Docker Networks
networks:
    sigga-network:
        driver:
            bridge